import json

JSONL_PATH = "/home/choeboeun0625/sqld-tutor/backend/app/data/questions/questions_v0.1.jsonl"

questions = [
# ── 계층형 쿼리 q136~q143 ──────────────────────────────────────
{
  "id":"q136","subject":"SQL 기본 및 활용","main_category":"SQL 활용",
  "sub_category":"계층형 쿼리","category":"SQL 활용 기타","question_type":"A",
  "context":None,
  "question":"다음 중 CONNECT_BY_ISLEAF 함수에 대한 설명으로 올바른 것은?",
  "options":{"1":"현재 행이 루트 노드이면 1, 아니면 0을 반환한다.",
             "2":"현재 행이 리프(Leaf) 노드이면 1, 아니면 0을 반환한다.",
             "3":"현재 행이 리프 노드이면 0, 아니면 1을 반환한다.",
             "4":"현재 행의 계층 레벨(깊이)을 숫자로 반환한다."},
  "answer":2,
  "hint":"리프(Leaf) 노드는 자식이 없는 말단 노드다.",
  "explanation":"CONNECT_BY_ISLEAF는 현재 행이 리프 노드(자식 노드가 없는 말단)이면 1, 자식이 있으면 0을 반환한다. 루트 여부는 CONNECT_BY_ROOT로 확인하고, 레벨 깊이는 LEVEL 의사 컬럼을 사용한다.",
  "tags":["계층형쿼리","CONNECT_BY_ISLEAF","리프노드"],"difficulty":"중","pass_rate":None,"created_at":"2026-06-16","verified":True
},
{
  "id":"q137","subject":"SQL 기본 및 활용","main_category":"SQL 활용",
  "sub_category":"계층형 쿼리","category":"SQL 활용 기타","question_type":"A",
  "context":None,
  "question":"계층형 쿼리에서 NOCYCLE 옵션을 사용하는 이유로 가장 올바른 것은?",
  "options":{"1":"계층 구조에서 중복 데이터를 제거하기 위해 사용한다.",
             "2":"특정 레벨 이하의 데이터를 조회하지 않기 위해 사용한다.",
             "3":"계층 구조에서 순환(사이클)이 발생할 경우 무한 루프를 방지하기 위해 사용한다.",
             "4":"계층 구조에서 리프 노드만 선택적으로 조회하기 위해 사용한다."},
  "answer":3,
  "hint":"데이터에 A→B→A처럼 순환 참조가 있을 때 문제가 발생한다.",
  "explanation":"NOCYCLE 옵션은 계층형 쿼리 전개 중 순환(사이클)이 발생했을 때 무한 루프를 방지하고 해당 순환이 시작되는 행까지만 조회한다. 사이클이 발생한 행은 CONNECT_BY_ISCYCLE 의사 컬럼으로 확인할 수 있다.",
  "tags":["계층형쿼리","NOCYCLE","순환참조"],"difficulty":"중","pass_rate":None,"created_at":"2026-06-16","verified":True
},
{
  "id":"q138","subject":"SQL 기본 및 활용","main_category":"SQL 활용",
  "sub_category":"계층형 쿼리","category":"SQL 활용 기타","question_type":"A",
  "context":None,
  "question":"계층형 쿼리에서 LEVEL 의사 컬럼에 대한 설명으로 올바르지 않은 것은?",
  "options":{"1":"루트 노드의 LEVEL 값은 1이다.",
             "2":"WHERE LEVEL <= 3 조건으로 3레벨 이하 데이터만 조회할 수 있다.",
             "3":"LEVEL 값이 클수록 루트 노드에 가깝다.",
             "4":"LEVEL은 SELECT 절과 WHERE 절 모두에서 사용할 수 있다."},
  "answer":3,
  "hint":"LEVEL은 루트에서 멀어질수록 커진다.",
  "explanation":"LEVEL은 루트 노드가 1이고 자식 노드로 내려갈수록 값이 커진다. 즉 LEVEL이 클수록 루트에서 멀어지는 것이다. '루트에 가깝다'는 설명은 반대로 되어 있어 틀렸다.",
  "tags":["계층형쿼리","LEVEL","의사컬럼"],"difficulty":"하","pass_rate":None,"created_at":"2026-06-16","verified":True
},
{
  "id":"q139","subject":"SQL 기본 및 활용","main_category":"SQL 활용",
  "sub_category":"계층형 쿼리","category":"SQL 활용 기타","question_type":"A",
  "context":None,
  "question":"SYS_CONNECT_BY_PATH(컬럼, 구분자)에 대한 설명으로 올바른 것은?",
  "options":{"1":"현재 노드부터 리프 노드까지의 경로를 반환한다.",
             "2":"루트 노드부터 현재 노드까지의 경로를 구분자로 연결하여 반환한다.",
             "3":"현재 노드의 형제 노드들의 이름을 구분자로 연결하여 반환한다.",
             "4":"루트 노드의 이름만 반환한다."},
  "answer":2,
  "hint":"SYS_CONNECT_BY_PATH는 루트→현재까지의 전체 경로를 보여준다.",
  "explanation":"SYS_CONNECT_BY_PATH(컬럼, 구분자)는 루트 노드부터 현재 노드까지의 계층 경로를 구분자로 연결하여 반환한다. 예: '/A/B/C' 형태로 출력된다. 계층형 쿼리(CONNECT BY) 내에서만 사용 가능하다.",
  "tags":["계층형쿼리","SYS_CONNECT_BY_PATH","경로"],"difficulty":"중","pass_rate":None,"created_at":"2026-06-16","verified":True
},
{
  "id":"q140","subject":"SQL 기본 및 활용","main_category":"SQL 활용",
  "sub_category":"계층형 쿼리","category":"SQL 활용 기타","question_type":"A",
  "context":"EMP 테이블에 EMPNO(사원번호)와 MGR(직속 상관의 EMPNO) 컬럼이 있다. 최상위 관리자(MGR IS NULL)부터 아래로 전개하는 순방향 계층 쿼리를 작성하려 한다.",
  "question":"다음 중 순방향 계층 전개를 위한 CONNECT BY 절로 올바른 것은?",
  "options":{"1":"CONNECT BY PRIOR EMPNO = MGR",
             "2":"CONNECT BY PRIOR MGR = EMPNO",
             "3":"CONNECT BY EMPNO = MGR",
             "4":"CONNECT BY MGR = PRIOR EMPNO"},
  "answer":1,
  "hint":"순방향: 현재 행의 EMPNO가 다음 행의 MGR이 되어야 한다.",
  "explanation":"순방향 계층 전개(루트→리프)는 CONNECT BY PRIOR EMPNO = MGR로 표현한다. PRIOR는 이전(부모) 행을 참조하므로 '부모의 EMPNO = 현재 행의 MGR' 관계로 연결된다. PRIOR MGR = EMPNO는 역방향(리프→루트) 전개다.",
  "tags":["계층형쿼리","PRIOR","순방향","역방향"],"difficulty":"중","pass_rate":None,"created_at":"2026-06-16","verified":True
},
{
  "id":"q141","subject":"SQL 기본 및 활용","main_category":"SQL 활용",
  "sub_category":"계층형 쿼리","category":"SQL 활용 기타","question_type":"A",
  "context":None,
  "question":"계층형 쿼리에서 WHERE 절과 START WITH 절의 차이에 대한 설명으로 올바른 것은?",
  "options":{"1":"WHERE 절은 계층 전개 전에 필터링되고, START WITH 절은 계층 전개 후에 필터링된다.",
             "2":"START WITH 절은 시작 노드를 결정하고, WHERE 절은 계층 전개가 완료된 후 결과를 필터링한다.",
             "3":"WHERE 절과 START WITH 절은 동일한 시점에 동시에 필터링된다.",
             "4":"WHERE 절이 START WITH 절보다 항상 먼저 실행된다."},
  "answer":2,
  "hint":"계층 전개 순서: START WITH → CONNECT BY 전개 → WHERE 필터",
  "explanation":"START WITH 절은 계층 전개의 시작 노드를 결정하고, CONNECT BY 절로 전개가 완료된 후에 WHERE 절이 적용된다. 따라서 WHERE로 중간 노드를 제거해도 해당 노드의 자식은 이미 전개된 상태다. 시작 노드 자체를 제외하려면 START WITH를 수정해야 한다.",
  "tags":["계층형쿼리","WHERE","START WITH","필터순서"],"difficulty":"상","pass_rate":None,"created_at":"2026-06-16","verified":True
},
{
  "id":"q142","subject":"SQL 기본 및 활용","main_category":"SQL 활용",
  "sub_category":"계층형 쿼리","category":"SQL 활용 기타","question_type":"A",
  "context":None,
  "question":"계층형 쿼리에서 ORDER SIBLINGS BY에 대한 설명으로 올바른 것은?",
  "options":{"1":"계층 구조 자체를 재정렬하여 부모-자식 관계를 변경한다.",
             "2":"계층 구조를 무시하고 전체 결과를 일반 ORDER BY처럼 정렬한다.",
             "3":"동일한 부모를 가진 형제 노드들 사이에서만 정렬을 수행하며 계층 구조는 유지된다.",
             "4":"루트 노드부터 리프 노드까지의 순서를 역방향으로 변경한다."},
  "answer":3,
  "hint":"SIBLINGS는 '형제'라는 의미다.",
  "explanation":"ORDER SIBLINGS BY는 계층 구조를 유지하면서 같은 부모를 가진 형제 노드 간에만 정렬을 적용한다. 일반 ORDER BY를 사용하면 계층 구조가 무너지므로 계층형 쿼리에서는 반드시 ORDER SIBLINGS BY를 사용해야 한다.",
  "tags":["계층형쿼리","ORDER SIBLINGS BY","정렬"],"difficulty":"중","pass_rate":None,"created_at":"2026-06-16","verified":True
},
{
  "id":"q143","subject":"SQL 기본 및 활용","main_category":"SQL 활용",
  "sub_category":"계층형 쿼리","category":"SQL 활용 기타","question_type":"A",
  "context":None,
  "question":"다음 SQL에서 CONNECT_BY_ROOT 함수의 역할로 올바른 것은?\nSELECT EMPNO, CONNECT_BY_ROOT EMPNO AS ROOT_EMP\nFROM EMP\nSTART WITH MGR IS NULL\nCONNECT BY PRIOR EMPNO = MGR;",
  "options":{"1":"현재 행의 직접 상위 노드(부모)의 EMPNO를 반환한다.",
             "2":"현재 행이 속한 계층 트리의 루트 노드 EMPNO를 반환한다.",
             "3":"현재 행이 리프 노드인지 여부(1 또는 0)를 반환한다.",
             "4":"계층 전체에서 가장 깊은 레벨에 있는 EMPNO를 반환한다."},
  "answer":2,
  "hint":"ROOT = 뿌리, 즉 가장 위에 있는 노드",
  "explanation":"CONNECT_BY_ROOT 연산자는 현재 행이 속한 계층 트리의 루트 노드 값을 반환한다. 여러 개의 루트가 있는 경우 각 행이 속한 트리의 루트 값을 각각 반환한다. 부모 노드는 PRIOR 키워드로 참조한다.",
  "tags":["계층형쿼리","CONNECT_BY_ROOT","루트노드"],"difficulty":"중","pass_rate":None,"created_at":"2026-06-16","verified":True
},

# ── WINDOW 함수 q144~q153 ─────────────────────────────────────
{
  "id":"q144","subject":"SQL 기본 및 활용","main_category":"SQL 활용",
  "sub_category":"윈도우 함수","category":"윈도우 함수","question_type":"A",
  "context":None,
  "question":"다음 중 LAG 함수와 LEAD 함수에 대한 설명으로 올바르지 않은 것은?",
  "options":{"1":"LAG 함수는 현재 행 기준으로 이전 행의 값을 반환한다.",
             "2":"LEAD 함수는 현재 행 기준으로 이후 행의 값을 반환한다.",
             "3":"LAG(SAL, 2)는 현재 행에서 2행 이전의 SAL 값을 반환한다.",
             "4":"LAG와 LEAD는 집계 함수이므로 반드시 GROUP BY와 함께 사용해야 한다."},
  "answer":4,
  "hint":"LAG/LEAD는 집계 함수가 아닌 윈도우(분석) 함수다.",
  "explanation":"LAG와 LEAD는 윈도우 함수(분석 함수)로 GROUP BY 없이 OVER() 절과 함께 사용한다. LAG는 이전 행, LEAD는 이후 행의 값을 가져오며, 두 번째 인자로 몇 행 이전/이후인지 지정할 수 있다(기본값 1).",
  "tags":["윈도우함수","LAG","LEAD"],"difficulty":"중","pass_rate":None,"created_at":"2026-06-16","verified":True
},
{
  "id":"q145","subject":"SQL 기본 및 활용","main_category":"SQL 활용",
  "sub_category":"윈도우 함수","category":"윈도우 함수","question_type":"A",
  "context":None,
  "question":"FIRST_VALUE(SAL) OVER (PARTITION BY DEPTNO ORDER BY SAL ASC)에 대한 설명으로 올바른 것은?",
  "options":{"1":"전체 데이터에서 SAL이 가장 작은 값을 반환한다.",
             "2":"각 DEPTNO 파티션 내에서 SAL 오름차순 기준 첫 번째(최솟값) SAL을 모든 행에 반환한다.",
             "3":"각 DEPTNO 파티션 내에서 현재 행의 SAL 값을 반환한다.",
             "4":"각 DEPTNO 파티션 내에서 SAL이 가장 큰 값을 반환한다."},
  "answer":2,
  "hint":"FIRST_VALUE = 윈도우 프레임 내 첫 번째 값, ORDER BY ASC이면 최솟값",
  "explanation":"FIRST_VALUE는 윈도우 프레임의 첫 번째 행 값을 반환한다. PARTITION BY DEPTNO로 부서별로 나누고 ORDER BY SAL ASC로 정렬하면 각 부서 내 SAL 최솟값이 모든 행에 반복 반환된다. LAST_VALUE는 마지막 행 값을 반환한다.",
  "tags":["윈도우함수","FIRST_VALUE","LAST_VALUE"],"difficulty":"중","pass_rate":None,"created_at":"2026-06-16","verified":True
},
{
  "id":"q146","subject":"SQL 기본 및 활용","main_category":"SQL 활용",
  "sub_category":"윈도우 함수","category":"윈도우 함수","question_type":"A",
  "context":"[점수 테이블: A=100점, B=100점, C=80점]을 점수 내림차순으로 순위를 매긴다.",
  "question":"RANK, DENSE_RANK, ROW_NUMBER 각 함수의 결과로 올바른 것은?",
  "options":{"1":"RANK: A=1,B=1,C=2 / DENSE_RANK: A=1,B=1,C=3 / ROW_NUMBER: A=1,B=2,C=3",
             "2":"RANK: A=1,B=1,C=3 / DENSE_RANK: A=1,B=1,C=2 / ROW_NUMBER: A=1,B=2,C=3",
             "3":"RANK: A=1,B=2,C=3 / DENSE_RANK: A=1,B=1,C=2 / ROW_NUMBER: A=1,B=1,C=2",
             "4":"RANK: A=1,B=1,C=3 / DENSE_RANK: A=1,B=2,C=3 / ROW_NUMBER: A=1,B=2,C=3"},
  "answer":2,
  "hint":"RANK는 동점 다음 순위를 건너뛰고, DENSE_RANK는 건너뛰지 않는다.",
  "explanation":"RANK: 동점(A=B=1위)이면 다음 순위를 건너뛰어 C=3위. DENSE_RANK: 동점 후 바로 다음 순위이므로 C=2위. ROW_NUMBER: 동점 무관 행 번호 순서대로 A=1, B=2, C=3.",
  "tags":["윈도우함수","RANK","DENSE_RANK","ROW_NUMBER"],"difficulty":"중","pass_rate":None,"created_at":"2026-06-16","verified":True
},
{
  "id":"q147","subject":"SQL 기본 및 활용","main_category":"SQL 활용",
  "sub_category":"윈도우 함수","category":"윈도우 함수","question_type":"A",
  "context":None,
  "question":"윈도우 프레임에서 ROWS와 RANGE의 차이에 대한 설명으로 올바른 것은?",
  "options":{"1":"ROWS는 ORDER BY 컬럼 값의 범위 기준으로, RANGE는 물리적 행 수 기준으로 윈도우를 정의한다.",
             "2":"ROWS는 물리적 행 수 기준으로, RANGE는 ORDER BY 컬럼 값의 범위 기준으로 윈도우를 정의한다.",
             "3":"ROWS와 RANGE는 ORDER BY 컬럼에 중복 값이 없으면 항상 동일한 결과를 반환한다.",
             "4":"RANGE는 ORDER BY 없이도 사용할 수 있지만 ROWS는 반드시 ORDER BY가 필요하다."},
  "answer":2,
  "hint":"ROWS = 행 번호 기준, RANGE = 값 범위 기준. 동점 행이 있을 때 차이가 난다.",
  "explanation":"ROWS는 물리적 행 번호 기준(예: 1 PRECEDING은 바로 이전 1행), RANGE는 ORDER BY 컬럼 값의 범위 기준(예: 1 PRECEDING은 현재 값에서 1 작은 값까지)으로 윈도우를 정의한다. 동점 값이 있을 때 RANGE는 해당 값들을 모두 포함할 수 있어 결과가 달라진다.",
  "tags":["윈도우함수","ROWS","RANGE","프레임"],"difficulty":"상","pass_rate":None,"created_at":"2026-06-16","verified":True
},
{
  "id":"q148","subject":"SQL 기본 및 활용","main_category":"SQL 활용",
  "sub_category":"윈도우 함수","category":"윈도우 함수","question_type":"A",
  "context":None,
  "question":"NTILE(4) OVER (ORDER BY SAL DESC)에 대한 설명으로 올바른 것은?",
  "options":{"1":"SAL 상위 4개의 행만 반환한다.",
             "2":"전체 행을 SAL 내림차순으로 정렬한 후 4개의 그룹으로 나눠 그룹 번호(1~4)를 반환한다.",
             "3":"SAL이 동일한 경우 동일한 NTILE 값을 부여하고 다음 그룹 번호를 건너뛴다.",
             "4":"NTILE(4)는 전체 행 수가 반드시 4의 배수여야 정상 동작한다."},
  "answer":2,
  "hint":"NTILE(n)은 전체를 n등분하는 함수다.",
  "explanation":"NTILE(n)은 결과 행을 ORDER BY 기준으로 정렬한 후 n개의 그룹으로 균등 분할하여 각 행에 그룹 번호(1~n)를 부여한다. 행 수가 n으로 나누어떨어지지 않으면 앞 그룹에 1개씩 더 배분한다. 동점 처리는 별도로 하지 않는다.",
  "tags":["윈도우함수","NTILE","그룹분할"],"difficulty":"중","pass_rate":None,"created_at":"2026-06-16","verified":True
},
{
  "id":"q149","subject":"SQL 기본 및 활용","main_category":"SQL 활용",
  "sub_category":"윈도우 함수","category":"윈도우 함수","question_type":"A",
  "context":None,
  "question":"SUM(SAL) OVER()에 대한 설명으로 올바른 것은?",
  "options":{"1":"현재 행의 SAL 값만 반환한다.",
             "2":"PARTITION BY가 없으므로 문법 오류가 발생한다.",
             "3":"전체 데이터를 하나의 파티션으로 간주하여 SAL의 전체 합계를 모든 행에 반환한다.",
             "4":"ORDER BY가 없으면 OVER() 절 자체를 사용할 수 없다."},
  "answer":3,
  "hint":"OVER() 안이 비어 있으면 전체가 하나의 파티션",
  "explanation":"OVER() 안에 아무것도 없으면 전체 결과 집합을 하나의 파티션으로 처리한다. 따라서 SUM(SAL) OVER()는 전체 SAL 합계를 모든 행에 동일하게 반환한다. PARTITION BY, ORDER BY 모두 선택 사항이다.",
  "tags":["윈도우함수","OVER","파티션"],"difficulty":"중","pass_rate":None,"created_at":"2026-06-16","verified":True
},
{
  "id":"q150","subject":"SQL 기본 및 활용","main_category":"SQL 활용",
  "sub_category":"윈도우 함수","category":"윈도우 함수","question_type":"A",
  "context":None,
  "question":"다음 중 윈도우 프레임 문법으로 올바르지 않은 것은?",
  "options":{"1":"ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW",
             "2":"RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING",
             "3":"ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING",
             "4":"RANGE BETWEEN UNBOUNDED FOLLOWING AND UNBOUNDED PRECEDING"},
  "answer":4,
  "hint":"프레임의 시작점은 끝점보다 앞서야 한다.",
  "explanation":"윈도우 프레임에서 BETWEEN start AND end 형식에서 start는 end보다 앞서야 한다. UNBOUNDED FOLLOWING은 파티션의 마지막 행을 의미하므로 시작점(start)으로 사용할 수 없다. 또한 UNBOUNDED PRECEDING은 시작점, UNBOUNDED FOLLOWING은 끝점에만 사용 가능하다.",
  "tags":["윈도우함수","프레임","UNBOUNDED"],"difficulty":"상","pass_rate":None,"created_at":"2026-06-16","verified":True
},
{
  "id":"q151","subject":"SQL 기본 및 활용","main_category":"SQL 활용",
  "sub_category":"윈도우 함수","category":"윈도우 함수","question_type":"A",
  "context":None,
  "question":"다음 중 윈도우 함수에 대한 설명으로 올바르지 않은 것은?",
  "options":{"1":"윈도우 함수는 WHERE 절에서 직접 사용할 수 없다.",
             "2":"윈도우 함수는 SELECT 절과 ORDER BY 절에서 사용할 수 있다.",
             "3":"윈도우 함수는 GROUP BY와 함께 사용할 수 있다.",
             "4":"윈도우 함수 결과를 WHERE 절에서 바로 필터링할 수 있다."},
  "answer":4,
  "hint":"윈도우 함수는 SELECT 처리 후 계산되므로 WHERE에서 직접 참조 불가",
  "explanation":"윈도우 함수는 SELECT 절에서 계산되므로 WHERE 절에서 직접 필터링할 수 없다. 윈도우 함수 결과를 WHERE로 필터링하려면 인라인 뷰(서브쿼리)나 CTE(WITH 절)로 감싸야 한다. HAVING 절에서도 윈도우 함수를 직접 사용할 수 없다.",
  "tags":["윈도우함수","WHERE","필터링제한"],"difficulty":"중","pass_rate":None,"created_at":"2026-06-16","verified":True
},
{
  "id":"q152","subject":"SQL 기본 및 활용","main_category":"SQL 활용",
  "sub_category":"윈도우 함수","category":"윈도우 함수","question_type":"A",
  "context":None,
  "question":"윈도우 함수의 PARTITION BY와 GROUP BY의 차이에 대한 설명으로 올바른 것은?",
  "options":{"1":"PARTITION BY는 결과 행 수를 줄이고, GROUP BY는 원본 행 수를 유지한다.",
             "2":"GROUP BY는 그룹별로 집계하여 행 수를 줄이고, PARTITION BY는 원본 행 수를 유지하면서 파티션별 계산 값을 각 행에 반환한다.",
             "3":"PARTITION BY와 GROUP BY는 항상 동일한 결과를 반환한다.",
             "4":"PARTITION BY는 반드시 ORDER BY와 함께 사용해야 하지만 GROUP BY는 단독 사용이 가능하다."},
  "answer":2,
  "hint":"GROUP BY는 행을 줄이고, PARTITION BY는 행을 유지한다.",
  "explanation":"GROUP BY는 그룹별 집계 결과로 행 수가 줄어든다. PARTITION BY는 원본 행 수를 그대로 유지하면서 각 행에 파티션 단위로 계산된 값(합계, 평균 등)을 추가로 반환한다. 이것이 윈도우 함수의 핵심 특징이다.",
  "tags":["윈도우함수","PARTITION BY","GROUP BY","차이"],"difficulty":"중","pass_rate":None,"created_at":"2026-06-16","verified":True
},
{
  "id":"q153","subject":"SQL 기본 및 활용","main_category":"SQL 활용",
  "sub_category":"윈도우 함수","category":"윈도우 함수","question_type":"A",
  "context":None,
  "question":"PERCENT_RANK()와 CUME_DIST()의 차이에 대한 설명으로 올바른 것은?",
  "options":{"1":"PERCENT_RANK의 최솟값은 0이고, CUME_DIST의 최솟값도 0이다.",
             "2":"PERCENT_RANK는 현재 행보다 큰 값의 비율, CUME_DIST는 현재 행보다 작거나 같은 값의 비율을 반환한다.",
             "3":"PERCENT_RANK의 최솟값은 0, 최댓값은 1이고, CUME_DIST의 최솟값은 0보다 크고 최댓값은 1이다.",
             "4":"두 함수 모두 동점 처리 시 RANK처럼 다음 순위를 건너뛴다."},
  "answer":3,
  "hint":"PERCENT_RANK = (순위-1)/(전체-1), CUME_DIST = 현재 이하 행수/전체 행수",
  "explanation":"PERCENT_RANK = (rank-1)/(n-1)이므로 첫 번째 행은 항상 0, 최댓값은 1이다. CUME_DIST = 현재 행 이하인 행 수/전체 행 수이므로 최솟값은 0보다 크고 최댓값은 1이다. CUME_DIST는 항상 0 초과 1 이하의 값을 가진다.",
  "tags":["윈도우함수","PERCENT_RANK","CUME_DIST"],"difficulty":"상","pass_rate":None,"created_at":"2026-06-16","verified":True
},

# ── GROUP BY 고급 q154~q161 ───────────────────────────────────
{
  "id":"q154","subject":"SQL 기본 및 활용","main_category":"SQL 기본",
  "sub_category":"그룹 함수","category":"GROUP BY & ORDER BY","question_type":"A",
  "context":None,
  "question":"GROUP BY ROLLUP(DEPTNO, JOB)을 사용할 때 생성되는 그룹 집합으로 올바른 것은?",
  "options":{"1":"(DEPTNO, JOB), (DEPTNO), ()",
             "2":"(DEPTNO, JOB), (JOB), ()",
             "3":"(DEPTNO, JOB), (DEPTNO), (JOB), ()",
             "4":"(DEPTNO, JOB), ()"},
  "answer":1,
  "hint":"ROLLUP(A,B)는 (A,B), (A), () 순서로 왼쪽부터 제거한다.",
  "explanation":"ROLLUP(DEPTNO, JOB)은 (DEPTNO, JOB) 소계, (DEPTNO) 소계, () 전체 합계의 3가지 그룹을 생성한다. ROLLUP은 오른쪽 컬럼부터 하나씩 제거하는 방식이다. (JOB) 단독 소계는 생성하지 않는다. 모든 조합이 필요하면 CUBE를 사용한다.",
  "tags":["ROLLUP","GROUP BY","소계","그룹함수"],"difficulty":"중","pass_rate":None,"created_at":"2026-06-16","verified":True
},
{
  "id":"q155","subject":"SQL 기본 및 활용","main_category":"SQL 기본",
  "sub_category":"그룹 함수","category":"GROUP BY & ORDER BY","question_type":"A",
  "context":None,
  "question":"GROUPING(컬럼명) 함수에 대한 설명으로 올바른 것은?",
  "options":{"1":"해당 컬럼이 GROUP BY 절에 포함되어 있으면 1, 아니면 0을 반환한다.",
             "2":"ROLLUP이나 CUBE에 의해 생성된 소계/합계 행에서 해당 컬럼이 집계에 사용된 경우 1, 실제 데이터 행이면 0을 반환한다.",
             "3":"해당 컬럼의 NULL 값 개수를 반환한다.",
             "4":"GROUPING 함수는 ROLLUP에서만 사용할 수 있고 CUBE나 GROUPING SETS에서는 사용할 수 없다."},
  "answer":2,
  "hint":"GROUPING()은 소계 행(NULL로 표시된 집계 행)을 구별하기 위해 사용한다.",
  "explanation":"GROUPING(컬럼)은 ROLLUP/CUBE/GROUPING SETS에 의해 생성된 소계·합계 행에서 해당 컬럼이 집계 결과로 NULL이 된 경우 1을 반환하고, 실제 데이터 값인 경우 0을 반환한다. 이를 통해 데이터의 NULL과 집계 행의 NULL을 구별할 수 있다.",
  "tags":["GROUPING","ROLLUP","CUBE","소계구별"],"difficulty":"중","pass_rate":None,"created_at":"2026-06-16","verified":True
},
{
  "id":"q156","subject":"SQL 기본 및 활용","main_category":"SQL 기본",
  "sub_category":"그룹 함수","category":"GROUP BY & ORDER BY","question_type":"A",
  "context":None,
  "question":"GROUP BY CUBE(A, B, C)를 사용할 때 생성되는 그룹 집합의 수로 올바른 것은?",
  "options":{"1":"3개","2":"4개","3":"7개","4":"8개"},
  "answer":4,
  "hint":"CUBE(n개 컬럼)의 그룹 집합 수 = 2^n",
  "explanation":"CUBE는 지정된 컬럼들의 모든 가능한 조합을 생성한다. 컬럼이 3개(A, B, C)이면 2^3 = 8가지 그룹 집합: (A,B,C), (A,B), (A,C), (B,C), (A), (B), (C), ()가 생성된다.",
  "tags":["CUBE","그룹집합","조합수"],"difficulty":"중","pass_rate":None,"created_at":"2026-06-16","verified":True
},
{
  "id":"q157","subject":"SQL 기본 및 활용","main_category":"SQL 기본",
  "sub_category":"그룹 함수","category":"GROUP BY & ORDER BY","question_type":"A",
  "context":None,
  "question":"다음 중 GROUP BY ROLLUP(DEPTNO, JOB)과 동일한 결과를 반환하는 SQL은?",
  "options":{"1":"GROUP BY GROUPING SETS((DEPTNO, JOB), (DEPTNO), ())",
             "2":"GROUP BY GROUPING SETS((DEPTNO, JOB), (JOB), ())",
             "3":"GROUP BY GROUPING SETS((DEPTNO, JOB), (DEPTNO), (JOB), ())",
             "4":"GROUP BY GROUPING SETS((DEPTNO), (JOB), ())"},
  "answer":1,
  "hint":"ROLLUP(A,B) = GROUPING SETS((A,B), (A), ())",
  "explanation":"ROLLUP(DEPTNO, JOB)은 (DEPTNO, JOB), (DEPTNO), () 3가지 그룹을 생성한다. 이를 GROUPING SETS로 표현하면 GROUPING SETS((DEPTNO, JOB), (DEPTNO), ())와 동일하다. (JOB) 단독 소계가 추가된 ③은 CUBE에 해당한다.",
  "tags":["ROLLUP","GROUPING SETS","동치변환"],"difficulty":"중","pass_rate":None,"created_at":"2026-06-16","verified":True
},
{
  "id":"q158","subject":"SQL 기본 및 활용","main_category":"SQL 기본",
  "sub_category":"그룹 함수","category":"GROUP BY & ORDER BY","question_type":"A",
  "context":None,
  "question":"HAVING 절과 WHERE 절의 차이에 대한 설명으로 올바르지 않은 것은?",
  "options":{"1":"WHERE 절은 GROUP BY 이전에, HAVING 절은 GROUP BY 이후에 필터링된다.",
             "2":"HAVING 절에서는 집계 함수를 사용할 수 있지만 WHERE 절에서는 집계 함수를 사용할 수 없다.",
             "3":"개별 행 필터링은 WHERE 절을 사용하는 것이 성능상 유리하다.",
             "4":"HAVING 절은 반드시 GROUP BY 절과 함께 사용해야만 한다."},
  "answer":4,
  "hint":"HAVING은 GROUP BY 없이도 전체를 하나의 그룹으로 보고 집계 조건을 적용할 수 있다.",
  "explanation":"HAVING 절은 GROUP BY 없이도 사용할 수 있다. GROUP BY 없이 HAVING을 사용하면 전체 데이터를 하나의 그룹으로 간주하고 집계 조건을 적용한다. 예: SELECT COUNT(*) FROM EMP HAVING COUNT(*) > 5;",
  "tags":["HAVING","WHERE","GROUP BY","실행순서"],"difficulty":"중","pass_rate":None,"created_at":"2026-06-16","verified":True
},
{
  "id":"q159","subject":"SQL 기본 및 활용","main_category":"SQL 기본",
  "sub_category":"그룹 함수","category":"GROUP BY & ORDER BY","question_type":"A",
  "context":None,
  "question":"ROLLUP(A, B)와 ROLLUP(B, A)의 결과에 대한 설명으로 올바른 것은?",
  "options":{"1":"두 SQL은 완전히 동일한 결과를 반환한다.",
             "2":"ROLLUP(A,B)는 (A,B),(A),() 소계를 생성하고, ROLLUP(B,A)는 (B,A),(B),() 소계를 생성하므로 소계 기준이 다르다.",
             "3":"ROLLUP은 컬럼 순서에 관계없이 항상 모든 조합의 소계를 생성한다.",
             "4":"ROLLUP(A,B)와 ROLLUP(B,A)는 전체 합계 행만 동일하고 나머지는 모두 다르다."},
  "answer":2,
  "hint":"ROLLUP은 왼쪽 컬럼 기준으로 소계를 만든다 — 순서가 중요하다.",
  "explanation":"ROLLUP은 컬럼 순서에 민감하다. ROLLUP(A,B)는 A별 소계와 전체 합계를 만들고, ROLLUP(B,A)는 B별 소계와 전체 합계를 만든다. 모든 조합의 소계가 필요하면 CUBE를 사용해야 한다.",
  "tags":["ROLLUP","컬럼순서","소계"],"difficulty":"중","pass_rate":None,"created_at":"2026-06-16","verified":True
},
{
  "id":"q160","subject":"SQL 기본 및 활용","main_category":"SQL 기본",
  "sub_category":"그룹 함수","category":"GROUP BY & ORDER BY","question_type":"A",
  "context":None,
  "question":"GROUP BY GROUPING SETS((A,B), (A), (B), ())와 동일한 결과를 반환하는 것은?",
  "options":{"1":"GROUP BY ROLLUP(A, B)",
             "2":"GROUP BY ROLLUP(B, A)",
             "3":"GROUP BY CUBE(A, B)",
             "4":"GROUP BY A, B"},
  "answer":3,
  "hint":"(A,B), (A), (B), () 4가지 조합 = CUBE(A,B)",
  "explanation":"CUBE(A, B)는 (A,B), (A), (B), () 4가지 그룹 집합을 모두 생성한다. 이것은 GROUPING SETS((A,B), (A), (B), ())와 동일하다. ROLLUP(A,B)는 (A,B), (A), ()만 생성하므로 다르다.",
  "tags":["CUBE","GROUPING SETS","동치변환"],"difficulty":"중","pass_rate":None,"created_at":"2026-06-16","verified":True
},
{
  "id":"q161","subject":"SQL 기본 및 활용","main_category":"SQL 기본",
  "sub_category":"그룹 함수","category":"GROUP BY & ORDER BY","question_type":"A",
  "context":None,
  "question":"다음 SQL의 실행 결과에 대한 설명으로 올바른 것은?\nSELECT COUNT(*) FROM EMP HAVING COUNT(*) > 5;",
  "options":{"1":"GROUP BY 절이 없으므로 문법 오류가 발생한다.",
             "2":"전체 행 수가 5보다 크면 전체 행 수를 1개의 행으로 반환하고, 5 이하이면 아무것도 반환하지 않는다.",
             "3":"각 행별로 COUNT(*)를 계산하여 5보다 큰 행만 반환한다.",
             "4":"HAVING 절에서 집계 함수를 사용할 수 없으므로 오류가 발생한다."},
  "answer":2,
  "hint":"GROUP BY 없는 HAVING = 전체를 하나의 그룹으로 처리",
  "explanation":"GROUP BY 없이 HAVING을 사용하면 전체 테이블을 하나의 그룹으로 처리한다. 전체 행 수가 5 초과이면 COUNT(*) 값을 반환하고, 5 이하이면 HAVING 조건이 거짓이므로 아무 행도 반환하지 않는다.",
  "tags":["HAVING","GROUP BY없이","집계"],"difficulty":"중","pass_rate":None,"created_at":"2026-06-16","verified":True
},
]

with open(JSONL_PATH, "a", encoding="utf-8") as f:
    for q in questions:
        f.write(json.dumps(q, ensure_ascii=False) + "\n")

total = sum(1 for _ in open(JSONL_PATH))
print(f"총 문제 수: {total}")
print(f"추가된 문제: {len(questions)}개 (q136~q161)")
